[theme]
# Primary accent color for interactive elements.
primaryColor = "#2d5480"

# Background color for the main content area.
backgroundColor = "#E4E3E3"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#c6d0d2"

# Color used for almost all text.
textColor = "#2d5480"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
